Sharing test cases for row filter
Big-Life-Lab/ODM pull request #166
Opened 2021-09-02 16:08 UTC by GauriSaran

Added test cases for the row filter.

2021-09-03 12:34 UTC, yulric requested changes
1. Can you update the `sharedWith` field to have only two organizations?
2. We renamed `filterValue` to `ruleValue`. Can you update the tests?
3. Lets try to be consistent with the set of tables, variables and organization we use in the tests.
    1. For tables, lets stick with `Sample` for single tables and `WWMeasure` and `Sample` for multiple tables
    2. For variables
        1. Sample table
            1. Number columns: `fieldSampleTempC` for single column and `fieldSampleTempC` and `storageTempC` for multiple columns
            2. String columns: `typeOther` for single column and `typeOther` and `collectionOther` for multiple columns
            3. Datetime columns:  `dateTimeStart` for single column and `dateTimeStart` and `dateTimeEnd` for multiple columns
        2. WWMeasure table
            1. Number columns: `value`
            2. String columns: `unitOther`
            3. Datetime columns:  `analysisDate`
4. You only need to include one test case for the entries I sent in the email. For example, rule 1 and rule 2 are testing the same thing. The organizations are different but we don't need to test that.
5. Remember that there's a difference between the `datetime` and `date` type in the ODM. For now, lets only check the **datetime** property
6. I forgot to say this in the email but for each type of interval (number, date etc.) there should be four test cases
    1. Both endpoint open
    2. Left endpoint open, right endpoint closed
    3. Left endpoint closed, right endpoint open
    4. Both endpoints closed
7. Can you format all the rule objects so that the order of the fields is,
    1. ruleID
    2. table
    3. variable
    4. ruleValue
    5. direction
    6. sharedWith
    This will make it easier to understand the rules. You can also remove the description and license fields.

2021-09-23 13:46 UTC, GauriSaran commented
Added test cases for row with mainfunction file.

2021-09-28 15:33 UTC, yulric requested changes
1. We should start managing dependencies using [pipenv](https://packaging.python.org/tutorials/managing-dependencies/)
2. Rename mainfunction.py to the name of the function that the user will use
3. Can you move all the tests into a folder called `sharing_tests` in the sharing folder?
4. No need to include the `description`  and license fields in the testcases since it's not used in the code.
5. The inputs, outputs and assets for each test case should be in the same location. For example, in the `testcases_row.py` file only the inputs for the rules parameter are present. Can you update this.
6. For the `sharedWith` field in the test rules, you only need to include two organizations. One organization will be the one passed as input to the function while the other is present to ensure that the code works correctly when multiple orgs are present in the `sharedWith` field.

2021-09-28 15:33 UTC, yulric commented on sharing/mainfunction.py
> +def create_dataset(rule,data=dataset, org= organization):
Can we rename this to `create_shared_dataset`?

The parameter names should follow whats defined README file in the `sharing_functions` branch.

Why are the parameters being defaulted to the variables you defined above?

2021-09-28 15:33 UTC, yulric commented on sharing/mainfunction.py
> +  """The function takes in data in form of a dictionary where the keys specify each table in the data and the value is the actual data in the
Let's follow [Google's Python style guide](https://google.github.io/styleguide/pyguide.html#s3.8.1-comments-in-doc-strings) for docstrings. Can you update this line to follow it?

2021-10-07 20:58 UTC, GauriSaran commented
@yulric Let's have at least 4 or a minimum of 3 rows so we can accommodate for range type of data where we can remove more than 1 row from the data based on a range. With only 2 rows we will get empty dataset mostly for range.
Also from our meeting with @DougManuel and you on Monday two weeks ago, I did not make any implicit removal of data based on primary and foreign keys anymore and left it to be explicitly declared based on table names and variable names in the schema. I asked that time as I was creating the outputs for the test cased if I should do implicit removal of data from other table based on primary and foreign key relationships when I was creating the outputs and Doug mentioned that he was not sure if we should go with implicit removal. So I left it for user to explicitly declare in the schema multiple tables together in a rule when they want to remove data.
I am not sure if you guys want me to remove data from other tables if there is primary and foreign key relationship?
Also changing the structure of dataset will require me to recreate all the outputs also and may be even test cases because test cases were based on the dataset that is currently used in the file.
Please confirm to me about number of rows and if you need an implicit removal from other table? Because that would also change the outputs.

2021-10-14 17:33 UTC, yulric commented
@GauriSaran I'm getting a bunch of pylint errors when for the file `testcases_row_final_single_table.py`. They're shown below:

************* Module testcases_row_final_single_table
testcases_row_final_single_table.py:131:74: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:135:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:206:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:277:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:279:0: C0301: Line too long (119/100) (line-too-long)
testcases_row_final_single_table.py:348:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:350:0: C0301: Line too long (102/100) (line-too-long)
testcases_row_final_single_table.py:419:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:421:0: C0301: Line too long (102/100) (line-too-long)
testcases_row_final_single_table.py:490:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:492:0: C0301: Line too long (102/100) (line-too-long)
testcases_row_final_single_table.py:561:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:563:0: C0301: Line too long (102/100) (line-too-long)
testcases_row_final_single_table.py:632:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:634:0: C0301: Line too long (105/100) (line-too-long)
testcases_row_final_single_table.py:703:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:705:0: C0301: Line too long (106/100) (line-too-long)
testcases_row_final_single_table.py:715:0: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:774:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:776:0: C0301: Line too long (106/100) (line-too-long)
testcases_row_final_single_table.py:845:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:847:0: C0301: Line too long (106/100) (line-too-long)
testcases_row_final_single_table.py:916:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:918:0: C0301: Line too long (131/100) (line-too-long)
testcases_row_final_single_table.py:987:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:989:0: C0301: Line too long (131/100) (line-too-long)
testcases_row_final_single_table.py:1058:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1060:0: C0301: Line too long (131/100) (line-too-long)
testcases_row_final_single_table.py:1129:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1131:0: C0301: Line too long (131/100) (line-too-long)
testcases_row_final_single_table.py:1200:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1202:0: C0301: Line too long (107/100) (line-too-long)
testcases_row_final_single_table.py:1271:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1345:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1347:142: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1347:0: C0301: Line too long (142/100) (line-too-long)
testcases_row_final_single_table.py:1416:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1418:143: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1418:0: C0301: Line too long (143/100) (line-too-long)
testcases_row_final_single_table.py:1487:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1489:145: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1489:0: C0301: Line too long (145/100) (line-too-long)
testcases_row_final_single_table.py:1558:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1560:135: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1560:0: C0301: Line too long (135/100) (line-too-long)
testcases_row_final_single_table.py:1561:47: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1629:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1631:127: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1631:0: C0301: Line too long (127/100) (line-too-long)
testcases_row_final_single_table.py:1632:56: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1701:80: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1701:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1703:127: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1703:0: C0301: Line too long (127/100) (line-too-long)
testcases_row_final_single_table.py:1704:56: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1705:0: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1773:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1775:0: C0301: Line too long (127/100) (line-too-long)
testcases_row_final_single_table.py:1776:56: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1844:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1846:127: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1846:0: C0301: Line too long (127/100) (line-too-long)
testcases_row_final_single_table.py:1847:64: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1916:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1918:0: C0301: Line too long (126/100) (line-too-long)
testcases_row_final_single_table.py:1919:64: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1988:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:1990:126: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:1990:0: C0301: Line too long (126/100) (line-too-long)
testcases_row_final_single_table.py:1991:64: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:2060:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:2062:126: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:2062:0: C0301: Line too long (126/100) (line-too-long)
testcases_row_final_single_table.py:2063:64: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:2132:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_row_final_single_table.py:2134:126: C0303: Trailing whitespace (trailing-whitespace)
testcases_row_final_single_table.py:2134:0: C0301: Line too long (126/100) (line-too-long)
testcases_row_final_single_table.py:2203:0: W0311: Bad indentation. Found 2 spaces, expected 4 (bad-indentation)
testcases_ro [...]

2021-10-14 18:06 UTC, yulric commented
@GauriSaran Sorry, I don't understand what you mean by the linter is not working? I ran the command `pylint ./testcases_row_final_single_table.py` and it gave the me the errors above?

2021-11-11 18:07 UTC, yulric approved these changes

2021-11-11 18:08 UTC, merged